# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ed05798a8afd69342320c903f294459c7afe6a294b5389239f08df067f845aad6effd3dcf51ca042e3a86db9c1bea20f3d3673688d5d07c04352979081357f

test:
  secret_key_base: 933f9f4a6c1e6e40ccb55d0a71a967142006438203fde9dacf7a70e4ba1b6b6eda7191c5ef767cdddec5bab691dd9d3f809a07a2695d37dbc1783120f4855d7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
